title: "Zahir's CS Journey"
email: zjchoudhry@gmail.com
description: >-
  Sharing my experience in Computer Science and documenting my journey.
baseurl: "" # keep empty for username.github.io
url: "" # once custom domain set
theme: minima
